        - name: Installing additional packages
          ansible.builtin.apt:
            name: 
            - nginx
            - git
            update-cache: yes
            cache_valid_time: 86400