
- name: all config
  become: yes
  hosts: nginx_host
  roles:
    - role: RedHat
      when: ansible_facts['os_family'] == "RedHat"
    - role: Debian
      when: ansible_facts['os_family'] == "Debian"
    