
- name: Server preconfig
  become: yes
  hosts: nginx_host
  tasks:

    - name: Installing nginx on RedHat servers

      block:


#        - name: Installing additional packages
#          ansible.builtin.yum:
#            name: epel-release
#            state: present
        
        - name: Installing additional packages
          ansible.builtin.yum:
            name: 
              - nginx
#              - ufw
              - git
            state: present
        
#        - name: Start service httpd, if not started
#          ansible.builtin.service:
#            name: ufw
#           state: started

#        - name: Allow http traffic
#         community.general.ufw:
#            rule: allow
#            port: '80' 
          
        - name: Remove index file
          ansible.builtin.file:
            path: /usr/share/nginx/html
            state: absent

        - name: Copy git repo
          ansible.builtin.git:
            repo: https://github.com/vadimbeznosenko/ceoluso.git
            dest: /usr/share/nginx/html/
            single_branch: yes
            version: master
      
        - name: Add text "deployed by Luxoft"
          ansible.builtin.lineinfile:
            path: /usr/share/nginx/html/index.html
            regexp: '^(.*)Ceoluso &copy; 2021 | All rights reserved by Mrh Rifat(.*)$' 
            line: 'deployed by Luxoft {{ ansible_date_time.date }}'
            backrefs: yes

        - name: Start service nginx, if not started
          ansible.builtin.service:
            name: nginx
            state: started
            enabled: yes

      when: ansible_facts['os_family'] == "RedHat"


    - name: Installing nginx on Debian servers

      block:

        - name: Installing additional packages
          ansible.builtin.apt:
            name: nginx
            update-cache: yes
            cache_valid_time: 86400

        - name: Allow http traffic
          community.general.ufw:
            rule: allow
            port: '80' 

        - name: Remove index file
          ansible.builtin.file:
            path: /var/www/html/
            state: absent

        - name: Copy git repo
          ansible.builtin.git:
            repo: https://github.com/vadimbeznosenko/ceoluso.git
            dest: /var/www/html/
            single_branch: yes
            version: master

        - name: Add text "deployed by Luxoft"
          ansible.builtin.lineinfile:
            path: /var/www/html/index.html
            regexp: '^(.*)Ceoluso &copy; 2021 | All rights reserved by Mrh Rifat(.*)$' 
            line: 'deployed by Luxoft {{ ansible_date_time.date }}'
            backrefs: yes

        - name: Start service nginx, if not started
          ansible.builtin.service:
            name: nginx
            state: started
            enabled: yes

      when: ansible_facts['os_family'] == "Debian"