        - name: Installing additional repos for Centos
          ansible.builtin.yum:
            name: epel-release
            state: present
        
        - name: Installing additional packages
          ansible.builtin.yum:
            name: 
              - nginx
              - ufw
              - git
            state: present